---
name: Upload

on:
  push:
    branches:
      - master
      
jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
        
      - name: Push to Pinata
        uses: aquiladev/ipfs-action@v0.3.1
        with:
          path: ./public
          service: pinata
          pinName: ${{secrets.PIN_NAME}}
          pinataKey: ${{secrets.PINATA_KEY}}
          pinataSecret: ${{secrets.PINATA_SECRET}}
