---
name: Push to IPFS
on:
  workflow_dispatch: null
  push:
    branches:
      - master
jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - uses: aquiladev/ipfs-action@v0.1.3
    - name: Push
      id: pinata
      with:
        path: ./public
        service: pinata
        pinName: ${{secrets.PIN_NAME}}
        pinataKey: ${{secrets.PINATA_KEY}}
        pinataSecret: ${{secrets.PINATA_SECRET}}
