---
name: Upload

on:
  workflow_dispatch: null
  push:
    branches:
      - main
      
jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4
        
      - name: Push to Pinata
        #uses: aquiladev/ipfs-action@v0.3.1
        uses: filebase/ipfs-action@a7be7925e1040c4e11b408fc007cb02f8360aefa
        with:
          path: ./public
          service: pinata
          pinName: ${{secrets.PIN_NAME}}
          pinataKey: ${{secrets.PINATA_KEY}}
          pinataSecret: ${{secrets.PINATA_SECRET}}
